### ISSUE TITLE
Not able to install nats-sub, nats-pub

### ISSUE THREAD

**Issue by quangthanh010290** [nats-io/go-nats-examples#27]
I've tried to evaluate NATS, but can install the NAT client.
```
thanh@gitlab~
└──▶ go get github.com/nats-io/go-nats-examples/tools/nats-sub
thanh@gitlab~
└──▶ nats-sub -s demo.nats.io subject_name
nats-sub: command not found

```

**Comment by ripienaar** [comment]
It's probably in your go bin path which is not in PATH by default.  

I'd instead download the latest release from here https://github.com/nats-io/jetstream/releases/tag/v0.0.19 and use `nats pub` and `nats sub` etc

**Comment by quangthanh010290** [comment]
> It's probably in your go bin path which is not in PATH by default.
> 
> I'd instead download the latest release from here https://github.com/nats-io/jetstream/releases/tag/v0.0.19 and use `nats pub` and `nats sub` etc

Thank you so much, I have a little bit confused that the official document is telling about using nats-sub/nats-pub. Anyway, your help solved my problem.

**Comment by ripienaar** [comment]
The new `nats` CLI is one we are working on to replace those nats-pub, nats-sub, nats-req etc, not done-done yet, but good enough to learn with :)
